title: Universo MW8
email: universomw8@contato.com.br
description: > # this means to ignore newlines until "baseurl:"
  Empresa baiana apaixonada por comunicação e tecnologia criativa, propondo soluções singulares, empáticas e inovadoras que agregam experiências disruptivas no cotidiano das pessoas, através de Digital Signage, aplicativos móveis e web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.universomw8.com.br" # the base hostname & protocol for your site
twitter_username: universomw8
facebook_page: universomw8
instagram_page: universomw8
github_username:  universo-mw8

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

sass:
  sass_dir: _sass
  style: compressed

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Empresa
    url: /empresa

gems: [jekyll-admin]

exclude: [
  'package.json',
  '_source',
  'node_modules',
  '.sass-cache',
  'README',
  'Gemfile',
  'Gemfile.lock',
  'config.rb',
  'vendor',
  'gulpfile.babel.js'
]
